### ISSUE TITLE
Makefile / build instructions?

### ISSUE THREAD

**Issue by Joeboy** [mika314/melonix#1]
Hi, just saw the video, looks awesome! Really hope you keep working on this.

It doesn't seem like there's a Makefile or any build instructions in the repo at the moment. Any chance of supplying those so we can play with it? Thanks!

**Comment by mika314** [comment]
Right. I am using my own build tool. I will write up some detailed instructions. Short version, from Linux:
- Install coddle from here: [https://github.com/coddle-cpp/coddle](https://github.com/coddle-cpp/coddle)
- install dependencies: ffmpeg, fftw, and SDL2
- type `coddle` from the source root directory to build

**Comment by mika314** [comment]
I added build instructions for Ubuntu 22.04:
https://github.com/mika314/melonix/blob/main/README.md
