### ISSUE TITLE
build fail in coddle

### ISSUE THREAD

**Issue by zkbqhuang** [mika314/melonix#4]
Hi bro, I'm not good at cpp, but very interested in this project
I'm having trouble with the last step in the build process.
Can you give me some help? 

The error is as follows:
//====================================================================================

$ coddle
Loading config: .coddle/remote/libraries.toml
clang++ -std=c++20 $(pkg-config --cflags fftw3 libavcodec libavformat libavutil libswresample sdl2) -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-unreachable-code-loop-increment -Wno-exit-time-destructors -Wno-padded -Wno-sign-conversion -Wno-shadow-field-in-constructor -Wno-reserved-identifier -Wno-zero-as-null-pointer-constant -Wno-old-style-cast -Wno-implicit-int-float-conversion -Wno-double-promotion -Wno-weak-vtables -Wall -Wextra -gdwarf-3 -O3 -march=native -I.coddle/libs_src -c ./app.cpp -o .coddle/app.cpp.o
clang++ -std=c++20 $(pkg-config --cflags fftw3 libavcodec libavformat libavutil libswresample sdl2) -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-unreachable-code-loop-increment -Wno-exit-time-destructors -Wno-padded -Wno-sign-conversion -Wno-shadow-field-in-constructor -Wno-reserved-identifier -Wno-zero-as-null-pointer-constant -Wno-old-style-cast -Wno-implicit-int-float-conversion -Wno-double-promotion -Wno-weak-vtables -Wall -Wextra -gdwarf-3 -O3 -march=native -I.coddle/libs_src -c ./imgui-impl-sdlrenderer.cpp -o .coddle/imgui-impl-sdlrenderer.cpp.o
clang++ -std=c++20 $(pkg-config --cflags fftw3 libavcodec libavformat libavutil libswresample sdl2) -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-unreachable-code-loop-increment -Wno-exit-time-destructors -Wno-padded -Wno-sign-conversion -Wno-shadow-field-in-constructor -Wno-reserved-identifier -Wno-zero-as-null-pointer-constant -Wno-old-style-cast -Wno-implicit-int-float-conversion -Wno-double-promotion -Wno-weak-vtables -Wall -Wextra -gdwarf-3 -O3 -march=native -I.coddle/libs_src -c ./spec.cpp -o .coddle/spec.cpp.o
clang++ -std=c++20 $(pkg-config --cflags fftw3 libavcodec libavformat libavutil libswresample sdl2) -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-unreachable-code-loop-increment -Wno-exit-time-destructors -Wno-padded -Wno-sign-conversion -Wno-shadow-field-in-constructor -Wno-reserved-identifier -Wno-zero-as-null-pointer-constant -Wno-old-style-cast -Wno-implicit-int-float-conversion -Wno-double-promotion -Wno-weak-vtables -Wall -Wextra -gdwarf-3 -O3 -march=native -I.coddle/libs_src -c ./spec-cache.cpp -o .coddle/spec-cache.cpp.o
clang++ -std=c++20 $(pkg-config --cflags fftw3 libavcodec libavformat libavutil libswresample sdl2) -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-unreachable-code-loop-increment -Wno-exit-time-destructors -Wno-padded -Wno-sign-conversion -Wno-shadow-field-in-constructor -Wno-reserved-identifier -Wno-zero-as-null-pointer-constant -Wno-old-style-cast -Wno-implicit-int-float-conversion -Wno-double-promotion -Wno-weak-vtables -Wall -Wextra -gdwarf-3 -O3 -march=native -I.coddle/libs_src -c ./main.cpp -o .coddle/main.cpp.o
warningwarning: : unknown warning option '-Wno-reserved-identifier'; did you mean '-Wno-reserved-id-macro'? [-Wunknown-warning-option]unknown warning option '-Wno-reserved-identifier'; did you mean '-Wno-reserved-id-macro'? [-Wunknown-warning-option]

warning: unknown warning option '-Wno-reserved-identifier'; did you mean '-Wno-reserved-id-macro'? [-Wunknown-warning-option]
warningwarning: : unknown warning option '-Wno-reserved-identifier'; did you mean '-Wno-reserved-id-macro'? [-Wunknown-warning-option]unknown warning option '-Wno-reserved-identifier'; did you mean '-Wno-reserved-id-macro'? [-Wunknown-warning-option]

In file included from ./imgui-impl-sdlrenderer.cpp:36:
In file included from /usr/include/SDL2/SDL.h:32:
In file included from /usr/include/SDL2/SDL_main.h:25:
/usr/include/SDL2/SDL_stdinc.h:440:9: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
        case 3:         *_p++ = _val;   /* fallthrough */
        ^
/usr/include/SDL2/SDL_stdinc.h:440:9: note: insert '[[fallthrough]];' to silence this warning
        case 3:         *_p++ = _val;   /* fallthrough */
        ^
        [[fallthrough]]; 
/usr/include/SDL2/SDL_stdinc.h:440:9: note: insert 'break;' to avoid fall-through
        case 3:         *_p++ = _val;   /* fallthrough */
        ^
        break; 
/usr/include/SDL2/SDL_stdinc.h:441:9: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
        case 2:         *_p++ = _val;   /* fallthrough */
        ^
/usr/include/SDL2/SDL_stdinc.h:441:9: note: insert '[[fallthrough]];' to silence this warning
        case 2:         *_p++ = _val;   /* fallthrough */
        ^
        [[fallthrough]]; 
/usr/include/SDL2/SDL_stdinc.h:441:9: note: insert 'break;' to avoid fall-through
        case 2:         *_p++ = _val;   /* fallthrough */
        ^
        break; 
/usr/include/SDL2/SDL_stdinc.h:442:9: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
        case 1:         *_p++ = _val;   /* fallthrough */
        ^
/usr/include/SDL2/SDL_stdinc.h:442:9: note: insert '[[fallthrough]];' to silence this warning
        case 1:         *_p++ = _val;   /* fallthrough */
        ^
        [[fallthrough]]; 
/usr/include/SDL2/SDL_stdinc.h:442:9: note: insert 'break;' to avoid fall-through
        case 1:         *_p++ = _val;   /* fallthrough */
        ^
        break; 
In file included from ./spec.cpp:1:
./spec.hpp:6:10: fatal error: 'span' file not found
#include <span>
         ^~~~~~
1 warning and 1 error generated.
In file included from ./spec-cache.cpp:1:
In file included from ./spec-cache.hpp:2:
./spec.hpp:6:10: fatal error: 'span' file not found
#include <span>
         ^~~~~~
In file included from ./app.cpp:1:
In file included from ./app.hpp:6:
In file included from ./spec-cache.hpp:2:
./spec.hpp:6:10: fatal error: 'span' file not found
#include <span>
         ^~~~~~
In file included from ./main.cpp:6:
In file included from ./app.hpp:6:
In file included from ./spec-cache.hpp:2:
./spec.hpp:6:10: fatal error: 'span' file not found
#include <span>
         ^~~~~~
1 warning and 1 error generated.
./imgui-impl-sdlrenderer.cpp:38:2: error: This backend requires SDL 2.0.17+ because of SDL_RenderGeometry() function
#error This backend requires SDL 2.0.17+ because of SDL_RenderGeometry() function
 ^
./imgui-impl-sdlrenderer.cpp:182:36: warning: cast from 'const char *' to 'const int *' increases required alignment from 1 to 4 [-Wcast-align]
                const int* color = (const int*)((const char*)(vtx_buffer + pcmd->VtxOffset) + IM_OFFSETOF(ImDrawVert, col)); // SDL 2.0.17 and 2.0.18
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./imgui-impl-sdlrenderer.cpp:187:17: error: use of undeclared identifier 'SDL_RenderGeometryRaw'
                SDL_RenderGeometryRaw(bd->SDLRenderer, tex,
                ^
./imgui-impl-sdlrenderer.cpp:223:46: error: use of undeclared identifier 'SDL_ScaleModeLinear'
    SDL_SetTextureScaleMode(bd->FontTexture, SDL_ScaleModeLinear);
                                             ^
5 warnings and 3 errors generated.
1 warning and 1 error generated.
1 warning and 1 error generated.
terminate called after throwing an instance of 'int'

//==========================================================================================

and my dependencies
//==========================================================================================
libfftw3-dev 已是最新版本 (3.3.8-2ubuntu1)。
pkg-config 已是最新版本 (0.29.1-0ubuntu4)。
clang 已是最新版本 (1:10.0-50~exp1)。
libsdl2-dev 已是最新版本 (2.0.10+dfsg1-3)。
git 已是最新版本 (1:2.25.1-1ubuntu3.6)。
libavcodec-dev 已是最新版本 (7:4.2.7-0ubuntu0.1)。
libavformat-dev 已是最新版本 (7:4.2.7-0ubuntu0.1)。
libavutil-dev 已是最新版本 (7:4.2.7-0ubuntu0.1)。
libswresample-dev 已是最新版本 (7:4.2.7-0ubuntu0.1)。

//==========================================================================================

Or you can release a stable executable version
thank you very much!!!

**Comment by mika314** [comment]
Looks like you need newer version of clang or C++ runtime.

Can you show `clang --version`? or you can see if you need to install latest ` libstdc++`

**Comment by zkbqhuang** [comment]
Thank you, I'll try. Please keep working on this project.
